import { type NextPage } from "next";
import Head from "next/head";
// import CityCard from "../components/CityCard";
import Router from "next/router";
import { useEffect, useState } from "react";

// import { trpc } from "../utils/trpc";
import { getOptionsForVote } from "../utils/getRandomCities";

const Home: NextPage = () => {
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const [firstNum, setFirstNum] = useState(0);
  const [secondNum, setSecondNum] = useState(0);

  useEffect(() => {
    const [first, second] = getOptionsForVote();
    if (first) setFirstNum(first);
    if (second) setSecondNum(second);
  }, []);

  return (
    <>
      <Head>
        <title>Derek Codes Where We Live</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen flex-col items-center justify-center bg-slate-700 p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-green-700 md:text-[5rem]">
          {"Pick Which Place You'd Rather Live"}
        </h1>
        <div className="flex h-full w-full items-end justify-center pt-6 text-2xl text-blue-500">
          {/* {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>} */}
          <div
            className="cursor-pointer"
            onClick={() => Router.push("/results")}
          >
            See Results
          </div>
        </div>
        <div className="mt-3 flex items-center justify-center gap-3 pt-3 text-center md:grid-cols-2 lg:w-2/3">
          {/* <CityCard
            name="NextJS"
            description="The React framework for production"
            documentation="https://nextjs.org/"
          /> */}
          {firstNum}
          <div className="text-2xl text-green-700">VS</div>
          {/* <CityCard
            name="TypeScript"
            description="The React framework for production"
            documentation="https://www.typescriptlang.org/"
          /> */}
          {secondNum}
        </div>
      </div>
    </>
  );
};

export default Home;
